name: Run Puppeteer Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        # Use npm cache only if package-lock.json exists
        cache: ${{ hashFiles('package-lock.json') != '' && 'npm' || '' }}
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm install
    
    - name: Create logs directory
      run: mkdir -p logs
    
    - name: Start server in background
      run: |
        echo "Starting server..." | tee -a logs/server.log
        npm start &
        echo "Waiting for server to be ready..." | tee -a logs/server.log
        sleep 10 # Give the server more time to start
    
    - name: Run browser tests
      run: |
        echo "Running browser tests..." | tee -a logs/tests.log
        npm run test:browser || echo "Browser tests failed" | tee -a logs/tests.log
    
    - name: Run accessibility tests
      run: |
        echo "Running accessibility tests..." | tee -a logs/tests.log
        npm run test:accessibility || echo "Accessibility tests failed" | tee -a logs/tests.log
      
    - name: Check if server is running
      run: |
        echo "Checking server status..." | tee -a logs/server.log
        if curl -s http://localhost:3000 > /dev/null; then
          echo "Server is running properly" | tee -a logs/server.log
        else
          echo "Server is not running" | tee -a logs/server.log
          exit 1
        fi

    - name: Upload logs on failure
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: server-logs
        path: |
          logs/
          npm-debug.log*
        retention-days: 5
        if-no-files-found: warn
